# This issue template is for use in opening issues that document breaking changes. This template should be used to create an issue by Microsoft product team members who are documenting a breaking change.
# 
# Bracketed text is a placeholder; replace the text with the requested information and remove the brackets before submitting the issue. Also, remove this comment before submitting the issue.

name: "ASP.NET Core breaking change"
description: Report a change in ASP.NET Core that breaks something that worked in a previous version. This form is intended to be used by the product team.
title: "[Breaking change]: "
labels: "Breaking change"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the breaking change.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of .NET introduced the breaking change?
      options:
        - .NET 8
        - .NET 9
        - .NET 10 Preview 7
        - .NET 10 RC 1
        - .NET 10 RC 2
        - .NET 10 GA
        - .NET 11 Preview 1
        - .NET 11 Preview 2
        - .NET 11 Preview 3
        - .NET 11 Preview 4
        - .NET 11 Preview 5
        - Other (please put exact version in description textbox)
    validations:
      required: true
  - type: textarea
    id: old-behavior
    attributes:
      label: Previous behavior
      description: Describe the previous behavior. Include code snippets if applicable.
    validations:
      required: true
  - type: textarea
    id: new-behavior
    attributes:
      label: New behavior
      description: Describe the new behavior. Include code snippets if applicable.
    validations:
      required: true
  - type: checkboxes
    id: change-type
    attributes:
      label: Type of breaking change
      description: This information will be used to label the issue appropriately. [(How do I decide?)](https://learn.microsoft.com/dotnet/core/compatibility/categories)
      options:
        - label: "**Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation."
        - label:  "**Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully."
        - label:  "**Behavioral change**: Existing binaries may behave differently at run time."
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for change
      description: Describe why the breaking change was introduced.
    validations:
      required: true
  - type: textarea
    id: recommended-action
    attributes:
      label: Recommended action
      description: Describe the recommended action an affected user should take, such as workarounds or examples of code changes.
    validations:
      required: true
  - type: textarea
    id: affected-apis
    attributes:
      label: Affected APIs
      description: List all the APIs affected by this change. For methods, clarify if it's all overloads or specific overloads.
      placeholder: None.
    validations:
      required: true
